---
- hosts: webserver
  become: yes
  tasks:
  - name: installing java8 on ubuntu
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: installing java8 on redhat
    yum:
      name: "{{myjavaonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"