---
- hosts: 172.31.16.201
  become: yes
  tasks:
  - name: install git 
    apt:
      name: git
      state: present

  - name: install tree
    apt:
      nameee: tree
      state: present
    ignore_errors: yes

  - name: install wget
    apt:
      name: wget
      state: present