---
- hosts: 172.31.16.201
  become: yes
  tasks:
  - include_tasks: myfile.yaml

  - name: insall apache2 on ubuntu slave
    apt:
      name: apache2
      state: present

  - name: start apache2 service on ubuntu node
    service:
      name: apache2
      state: restarted