---
- hosts: 172.31.16.201
  become: yes
  tasks:
  - include_tasks: myfile.yaml

  - name: insall apache2 on ubuntu slave
    apt:
      name: apache2
      state: present

  - name: start apache2 service on ubuntu node
    service:
      name: apache2
      state: restarted

  - name: coping file index.j2 to ansible ubuntu slave
    template:
      src: index.j2
      dest: /var/www/html/index.html
