---
- hosts: 172.31.16.201
  become: yes
  tasks:
  - include_tasks: myfile.yaml

  - name: insall apache2 on ubuntu slave
    apt:
      name: apache2
      state: present
    notify: webserverstart

  - name: coping file index.j2 to ansible ubuntu slave
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: webserverstart

  handlers:
    - name: webserverstart
      service:
        name: apache2
        state: restarted
