---
- hosts: all
  become: yes
  tasks:
  - name: install apache webserver on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"
  - name: start apache2 service on ubuntu
    service:
      name: apache2
      state: started
    when:  ansible_os_family =="Debian"


  - name: install httpd webserver on redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"
  - name: start httpd service on redhat
    systemd:
      name: httpd
      start: started
      enabled: yes
    when: ansible_os_family =="RedHat"