---
- hosts: webserver
  become: yes
  tasks:
  - name: install apache webserver on ubuntu
    apt:
      name: "{{myubuntuwebserver}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: start apache2 service on ubuntu
    service:
      name: "{{myubuntuwebserver}}"
      state: started
    when:  ansible_os_family =="Debian"


  - name: install httpd webserver on redhat
    yum:
      name: "{{myredhatwebserver}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: start httpd service on redhat
    service:
      name: "{{myredhatwebserver}}"
      state: started
      enabled: yes
    when: ansible_os_family =="RedHat"