---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name:
    ping:

  - name : i want to install apache2 webserver on all my hosts
    apt:
      name: apache2
      state: present
  - name: i want to start my webserver
    service:
      name: apache2
      state: started
  - name: installing tree package
    apt:
      name: tree
      state: present