---
- name: create tomcat group
  group:
    name: tomcat
    state: present

- name: create tomcat user
  user:
    name: tomcat
    comment: my tomcat
    home: /opt/tomcat
    shell: /bin/false
    group: tomcat

